<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fp_masterquiz"
 *
 * Auto generated by Extension Builder 2019-03-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Master-Quiz',
    'description' => 'A modern extension that offers quiz, polls and tests. Ajax support. The result can be displayed as a chart too. Supports 8 question modes.',
    'category' => 'plugin',
    'author' => 'Kurt Gusbeth',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
