# You can simply include this Route in your site configuration:
# imports:
#   - { resource: "EXT:fp_masterquiz/Configuration/Routes/Default.yaml" }
routeEnhancers:
  QuizPlugin:
    type: Extbase
    extension: FpMasterquiz
    plugin: Pi1
    routes:
      - { routePath: '/', _controller: 'FpMasterquiz::list' }
      -
        routePath: '/quiz/{quiz_title}'
        _controller: 'FpMasterquiz::show'
        _arguments:
          quiz_title: quiz
      -
        routePath: '/result/{quiz_title}'
        _controller: 'FpMasterquiz::result'
        _arguments:
          quiz_title: quiz
    defaultController: 'FpMasterquiz::list'
    aspects:
      quiz_title:
        type: PersistedAliasMapper
        tableName: tx_fpmasterquiz_domain_model_quiz
        routeFieldPattern: '^(?P<path_segment>.+)$'
        routeFieldResult: '{path_segment}'
        routeFieldName: path_segment
