services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fixpunkt\FpMasterquiz\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Fixpunkt\FpMasterquiz\Backend\EventListener\PreviewEventListener:
    tags:
      - name: "event.listener"
        identifier: 'fp_masterquiz/preview-rendering'